$table = $('#plantTable');

$(document).ready(function(){
   // $('#example').DataTable( {
     //   "pagingType": "full_numbers"
    //} );

    $('#plantTable').dataTable( {
        "pageLength": 10,
        "pagingType":"simple",
        "bInfo":false,
        "bLengthChange":false
    });
    $table.dataTable();

    var table = $('#plantTable').DataTable();
    $('#plantTable tbody').on('click', 'tr', function () {
        var data = table.row( this ).data();

        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }

          //alert( 'You clicked on '+data[0]+'\'s row' );
          //console.log("clicked"+data[0]);
          $("#plantImg").attr("src", "");
          if(data[0] == 1){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/bayabas.png");
              document.getElementById('plantLabel').innerText = apothecaryData[0].commonName;
              document.getElementById('sciname').innerText = apothecaryData[0].sciname;
              document.getElementById('commonName').innerText = apothecaryData[0].commonName;
              document.getElementById('clade').innerText = apothecaryData[0].clade;
              document.getElementById('division').innerText = apothecaryData[0].division;
              document.getElementById('plantOrder').innerText = apothecaryData[0].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[0].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[0].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[0].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[0].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[0].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[0].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[0].plantUse;
          }else if(data[0] == 2){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/lagundi.png");
              document.getElementById('plantLabel').innerText = apothecaryData[1].commonName;
              document.getElementById('sciname').innerText = apothecaryData[1].sciname;
              document.getElementById('commonName').innerText = apothecaryData[1].commonName;
              document.getElementById('clade').innerText = apothecaryData[1].clade;
              document.getElementById('division').innerText = apothecaryData[1].division;
              document.getElementById('plantOrder').innerText = apothecaryData[1].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[1].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[1].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[1].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[1].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[1].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[1].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[1].plantUse;
          }else if(data[0] == 3){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Garlic.png");
              document.getElementById('plantLabel').innerText = apothecaryData[2].commonName;
              document.getElementById('sciname').innerText = apothecaryData[2].sciname;
              document.getElementById('commonName').innerText = apothecaryData[2].commonName;
              document.getElementById('clade').innerText = apothecaryData[2].clade;
              document.getElementById('division').innerText = apothecaryData[2].division;
              document.getElementById('plantOrder').innerText = apothecaryData[2].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[2].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[2].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[2].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[2].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[2].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[2].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[2].plantUse;
        }else if(data[0] == 4){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/yerbabuena.png");
              document.getElementById('plantLabel').innerText = apothecaryData[3].commonName;
              document.getElementById('sciname').innerText = apothecaryData[3].sciname;
              document.getElementById('commonName').innerText = apothecaryData[3].commonName;
              document.getElementById('clade').innerText = apothecaryData[3].clade;
              document.getElementById('division').innerText = apothecaryData[3].division;
              document.getElementById('plantOrder').innerText = apothecaryData[3].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[3].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[3].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[3].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[3].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[3].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[3].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[3].plantUse;
        }else if(data[0] == 5){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Ampalaya.png");
              document.getElementById('plantLabel').innerText = apothecaryData[4].commonName;
              document.getElementById('sciname').innerText = apothecaryData[4].sciname;
              document.getElementById('commonName').innerText = apothecaryData[4].commonName;
              document.getElementById('clade').innerText = apothecaryData[4].clade;
              document.getElementById('division').innerText = apothecaryData[4].division;
              document.getElementById('plantOrder').innerText = apothecaryData[4].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[4].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[4].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[4].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[4].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[4].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[4].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[4].plantUse;
        }else if(data[0] == 6){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pancit.png");
              document.getElementById('plantLabel').innerText = apothecaryData[5].commonName;
              document.getElementById('sciname').innerText = apothecaryData[5].sciname;
              document.getElementById('commonName').innerText = apothecaryData[5].commonName;
              document.getElementById('clade').innerText = apothecaryData[5].clade;
              document.getElementById('division').innerText = apothecaryData[5].division;
              document.getElementById('plantOrder').innerText = apothecaryData[5].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[5].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[5].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[5].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[5].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[5].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[5].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[5].plantUse;
        }else if(data[0] == 7){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/tsitsirika.png");
              document.getElementById('plantLabel').innerText = apothecaryData[6].commonName;
              document.getElementById('sciname').innerText = apothecaryData[6].sciname;
              document.getElementById('commonName').innerText = apothecaryData[6].commonName;
              document.getElementById('clade').innerText = apothecaryData[6].clade;
              document.getElementById('division').innerText = apothecaryData[6].division;
              document.getElementById('plantOrder').innerText = apothecaryData[6].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[6].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[6].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[6].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[6].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[6].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[6].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[6].plantUse;
        }else if(data[0] == 8){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Ginger.png");
              document.getElementById('plantLabel').innerText = apothecaryData[7].commonName;
              document.getElementById('sciname').innerText = apothecaryData[7].sciname;
              document.getElementById('commonName').innerText = apothecaryData[7].commonName;
              document.getElementById('clade').innerText = apothecaryData[7].clade;
              document.getElementById('division').innerText = apothecaryData[7].division;
              document.getElementById('plantOrder').innerText = apothecaryData[7].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[7].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[7].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[7].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[7].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[7].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[7].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[7].plantUse;
        }else if(data[0] == 9){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/akapulko1.png");
              document.getElementById('plantLabel').innerText = apothecaryData[8].commonName;
              document.getElementById('sciname').innerText = apothecaryData[8].sciname;
              document.getElementById('commonName').innerText = apothecaryData[8].commonName;
              document.getElementById('clade').innerText = apothecaryData[8].clade;
              document.getElementById('division').innerText = apothecaryData[8].division;
              document.getElementById('plantOrder').innerText = apothecaryData[8].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[8].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[8].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[8].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[8].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[8].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[8].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[8].plantUse;
        }else if(data[0] == 10){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/horsetail.png");
              document.getElementById('plantLabel').innerText = apothecaryData[9].commonName;
              document.getElementById('sciname').innerText = apothecaryData[9].sciname;
              document.getElementById('commonName').innerText = apothecaryData[9].commonName;
              document.getElementById('clade').innerText = apothecaryData[9].clade;
              document.getElementById('division').innerText = apothecaryData[9].division;
              document.getElementById('plantOrder').innerText = apothecaryData[9].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[9].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[9].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[9].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[9].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[9].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[9].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[9].plantUse;
        }else if(data[0] == 11){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/PapayaFruit.png");
              document.getElementById('plantLabel').innerText = apothecaryData[10].commonName;
              document.getElementById('sciname').innerText = apothecaryData[10].sciname;
              document.getElementById('commonName').innerText = apothecaryData[10].commonName;
              document.getElementById('clade').innerText = apothecaryData[10].clade;
              document.getElementById('division').innerText = apothecaryData[10].division;
              document.getElementById('plantOrder').innerText = apothecaryData[10].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[10].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[10].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[10].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[10].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[10].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[10].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[10].plantUse;
        }else if(data[0] == 12){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Calamansi.png");
              document.getElementById('plantLabel').innerText = apothecaryData[11].commonName;
              document.getElementById('sciname').innerText = apothecaryData[11].sciname;
              document.getElementById('commonName').innerText = apothecaryData[11].commonName;
              document.getElementById('clade').innerText = apothecaryData[11].clade;
              document.getElementById('division').innerText = apothecaryData[11].division;
              document.getElementById('plantOrder').innerText = apothecaryData[11].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[11].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[11].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[11].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[11].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[11].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[11].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[11].plantUse;
        }else if(data[0] == 13){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Aloe.png");
              document.getElementById('plantLabel').innerText = apothecaryData[12].commonName;
              document.getElementById('sciname').innerText = apothecaryData[12].sciname;
              document.getElementById('commonName').innerText = apothecaryData[12].commonName;
              document.getElementById('clade').innerText = apothecaryData[12].clade;
              document.getElementById('division').innerText = apothecaryData[12].division;
              document.getElementById('plantOrder').innerText = apothecaryData[12].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[12].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[12].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[12].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[12].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[12].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[12].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[12].plantUse;
        }else if(data[0] == 14){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Rose.png");
              document.getElementById('plantLabel').innerText = apothecaryData[13].commonName;
              document.getElementById('sciname').innerText = apothecaryData[13].sciname;
              document.getElementById('commonName').innerText = apothecaryData[13].commonName;
              document.getElementById('clade').innerText = apothecaryData[13].clade;
              document.getElementById('division').innerText = apothecaryData[13].division;
              document.getElementById('plantOrder').innerText = apothecaryData[13].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[13].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[13].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[13].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[13].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[13].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[13].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[13].plantUse;
        }else if(data[0] == 15){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Cucumber.png");
              document.getElementById('plantLabel').innerText = apothecaryData[14].commonName;
              document.getElementById('sciname').innerText = apothecaryData[14].sciname;
              document.getElementById('commonName').innerText = apothecaryData[14].commonName;
              document.getElementById('clade').innerText = apothecaryData[14].clade;
              document.getElementById('division').innerText = apothecaryData[14].division;
              document.getElementById('plantOrder').innerText = apothecaryData[14].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[14].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[14].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[14].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[14].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[14].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[14].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[14].plantUse;
        }else if(data[0] == 16){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Coconut.png");
              document.getElementById('plantLabel').innerText = apothecaryData[15].commonName;
              document.getElementById('sciname').innerText = apothecaryData[15].sciname;
              document.getElementById('commonName').innerText = apothecaryData[15].commonName;
              document.getElementById('clade').innerText = apothecaryData[15].clade;
              document.getElementById('division').innerText = apothecaryData[15].division;
              document.getElementById('plantOrder').innerText = apothecaryData[15].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[15].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[15].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[15].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[15].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[15].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[15].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[15].plantUse;
        }else if(data[0] == 17){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/agoho.png");
              document.getElementById('plantLabel').innerText = apothecaryData[16].commonName;
              document.getElementById('sciname').innerText = apothecaryData[16].sciname;
              document.getElementById('commonName').innerText = apothecaryData[16].commonName;
              document.getElementById('clade').innerText = apothecaryData[16].clade;
              document.getElementById('division').innerText = apothecaryData[16].division;
              document.getElementById('plantOrder').innerText = apothecaryData[16].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[16].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[16].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[16].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[16].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[16].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[16].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[16].plantUse;
        }else if(data[0] == 18){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pine.png");
              document.getElementById('plantLabel').innerText = apothecaryData[17].commonName;
              document.getElementById('sciname').innerText = apothecaryData[17].sciname;
              document.getElementById('commonName').innerText = apothecaryData[17].commonName;
              document.getElementById('clade').innerText = apothecaryData[17].clade;
              document.getElementById('division').innerText = apothecaryData[17].division;
              document.getElementById('plantOrder').innerText = apothecaryData[17].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[17].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[17].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[17].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[17].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[17].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[17].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[17].plantUse;
        }else if(data[0] == 19){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Gabi.png");
              document.getElementById('plantLabel').innerText = apothecaryData[18].commonName;
              document.getElementById('sciname').innerText = apothecaryData[18].sciname;
              document.getElementById('commonName').innerText = apothecaryData[18].commonName;
              document.getElementById('clade').innerText = apothecaryData[18].clade;
              document.getElementById('division').innerText = apothecaryData[18].division;
              document.getElementById('plantOrder').innerText = apothecaryData[18].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[18].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[18].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[18].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[18].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[18].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[18].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[18].plantUse;
        }else if(data[0] == 20){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Carrot.png");
              document.getElementById('plantLabel').innerText = apothecaryData[19].commonName;
              document.getElementById('sciname').innerText = apothecaryData[19].sciname;
              document.getElementById('commonName').innerText = apothecaryData[19].commonName;
              document.getElementById('clade').innerText = apothecaryData[19].clade;
              document.getElementById('division').innerText = apothecaryData[19].division;
              document.getElementById('plantOrder').innerText = apothecaryData[19].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[19].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[19].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[19].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[19].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[19].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[19].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[19].plantUse;
        }else if(data[0] == 21){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Camote.png");
              document.getElementById('plantLabel').innerText = apothecaryData[20].commonName;
              document.getElementById('sciname').innerText = apothecaryData[20].sciname;
              document.getElementById('commonName').innerText = apothecaryData[20].commonName;
              document.getElementById('clade').innerText = apothecaryData[20].clade;
              document.getElementById('division').innerText = apothecaryData[20].division;
              document.getElementById('plantOrder').innerText = apothecaryData[20].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[20].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[20].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[20].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[20].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[20].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[20].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[20].plantUse;
        }else if(data[0] == 22){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Potato.png");
              document.getElementById('plantLabel').innerText = apothecaryData[21].commonName;
              document.getElementById('sciname').innerText = apothecaryData[21].sciname;
              document.getElementById('commonName').innerText = apothecaryData[21].commonName;
              document.getElementById('clade').innerText = apothecaryData[21].clade;
              document.getElementById('division').innerText = apothecaryData[21].division;
              document.getElementById('plantOrder').innerText = apothecaryData[21].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[21].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[21].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[21].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[21].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[21].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[21].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[21].plantUse;
        }else if(data[0] == 23){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/corn.png");
              document.getElementById('plantLabel').innerText = apothecaryData[22].commonName;
              document.getElementById('sciname').innerText = apothecaryData[22].sciname;
              document.getElementById('commonName').innerText = apothecaryData[22].commonName;
              document.getElementById('clade').innerText = apothecaryData[22].clade;
              document.getElementById('division').innerText = apothecaryData[22].division;
              document.getElementById('plantOrder').innerText = apothecaryData[22].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[22].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[22].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[22].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[22].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[22].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[22].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[22].plantUse;
        }else if(data[0] == 24){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/rice.png");
              document.getElementById('plantLabel').innerText = apothecaryData[23].commonName;
              document.getElementById('sciname').innerText = apothecaryData[23].sciname;
              document.getElementById('commonName').innerText = apothecaryData[23].commonName;
              document.getElementById('clade').innerText = apothecaryData[23].clade;
              document.getElementById('division').innerText = apothecaryData[23].division;
              document.getElementById('plantOrder').innerText = apothecaryData[23].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[23].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[23].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[23].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[23].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[23].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[23].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[23].plantUse;
        }else if(data[0] == 25){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Squash.png");
              document.getElementById('plantLabel').innerText = apothecaryData[24].commonName;
              document.getElementById('sciname').innerText = apothecaryData[24].sciname;
              document.getElementById('commonName').innerText = apothecaryData[24].commonName;
              document.getElementById('clade').innerText = apothecaryData[24].clade;
              document.getElementById('division').innerText = apothecaryData[24].division;
              document.getElementById('plantOrder').innerText = apothecaryData[24].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[24].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[24].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[24].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[24].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[24].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[24].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[24].plantUse;
        }else if(data[0] == 26){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/talong.png");
              document.getElementById('plantLabel').innerText = apothecaryData[25].commonName;
              document.getElementById('sciname').innerText = apothecaryData[25].sciname;
              document.getElementById('commonName').innerText = apothecaryData[25].commonName;
              document.getElementById('clade').innerText = apothecaryData[25].clade;
              document.getElementById('division').innerText = apothecaryData[25].division;
              document.getElementById('plantOrder').innerText = apothecaryData[25].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[25].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[25].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[25].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[25].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[25].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[25].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[25].plantUse;
        }else if(data[0] == 27){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/patola.png");
              document.getElementById('plantLabel').innerText = apothecaryData[26].commonName;
              document.getElementById('sciname').innerText = apothecaryData[26].sciname;
              document.getElementById('commonName').innerText = apothecaryData[26].commonName;
              document.getElementById('clade').innerText = apothecaryData[26].clade;
              document.getElementById('division').innerText = apothecaryData[26].division;
              document.getElementById('plantOrder').innerText = apothecaryData[26].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[26].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[26].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[26].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[26].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[26].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[26].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[26].plantUse;
        }else if(data[0] == 28){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/upo.png");
              document.getElementById('plantLabel').innerText = apothecaryData[27].commonName;
              document.getElementById('sciname').innerText = apothecaryData[27].sciname;
              document.getElementById('commonName').innerText = apothecaryData[27].commonName;
              document.getElementById('clade').innerText = apothecaryData[27].clade;
              document.getElementById('division').innerText = apothecaryData[27].division;
              document.getElementById('plantOrder').innerText = apothecaryData[27].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[27].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[27].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[27].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[27].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[27].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[27].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[27].plantUse;
        }else if(data[0] == 29){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/okra.png");
              document.getElementById('plantLabel').innerText = apothecaryData[28].commonName;
              document.getElementById('sciname').innerText = apothecaryData[28].sciname;
              document.getElementById('commonName').innerText = apothecaryData[28].commonName;
              document.getElementById('clade').innerText = apothecaryData[28].clade;
              document.getElementById('division').innerText = apothecaryData[28].division;
              document.getElementById('plantOrder').innerText = apothecaryData[28].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[28].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[28].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[28].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[28].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[28].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[28].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[28].plantUse;
        }else if(data[0] == 30){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Mango.png");
              document.getElementById('plantLabel').innerText = apothecaryData[29].commonName;
              document.getElementById('sciname').innerText = apothecaryData[29].sciname;
              document.getElementById('commonName').innerText = apothecaryData[29].commonName;
              document.getElementById('clade').innerText = apothecaryData[29].clade;
              document.getElementById('division').innerText = apothecaryData[29].division;
              document.getElementById('plantOrder').innerText = apothecaryData[29].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[29].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[29].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[29].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[29].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[29].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[29].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[29].plantUse;
        }else if(data[0] == 31){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/coffee.png");
              document.getElementById('plantLabel').innerText = apothecaryData[30].commonName;
              document.getElementById('sciname').innerText = apothecaryData[30].sciname;
              document.getElementById('commonName').innerText = apothecaryData[30].commonName;
              document.getElementById('clade').innerText = apothecaryData[30].clade;
              document.getElementById('division').innerText = apothecaryData[30].division;
              document.getElementById('plantOrder').innerText = apothecaryData[30].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[30].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[30].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[30].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[30].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[30].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[30].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[30].plantUse;
        }else if(data[0] == 32){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/peanut.png");
              document.getElementById('plantLabel').innerText = apothecaryData[31].commonName;
              document.getElementById('sciname').innerText = apothecaryData[31].sciname;
              document.getElementById('commonName').innerText = apothecaryData[31].commonName;
              document.getElementById('clade').innerText = apothecaryData[31].clade;
              document.getElementById('division').innerText = apothecaryData[31].division;
              document.getElementById('plantOrder').innerText = apothecaryData[31].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[31].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[31].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[31].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[31].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[31].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[31].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[31].plantUse;
        }else if(data[0] == 33){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Tomato.png");
              document.getElementById('plantLabel').innerText = apothecaryData[32].commonName;
              document.getElementById('sciname').innerText = apothecaryData[32].sciname;
              document.getElementById('commonName').innerText = apothecaryData[32].commonName;
              document.getElementById('clade').innerText = apothecaryData[32].clade;
              document.getElementById('division').innerText = apothecaryData[32].division;
              document.getElementById('plantOrder').innerText = apothecaryData[32].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[32].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[32].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[32].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[32].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[32].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[32].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[32].plantUse;
        }else if(data[0] == 34){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pinya.png");
              document.getElementById('plantLabel').innerText = apothecaryData[33].commonName;
              document.getElementById('sciname').innerText = apothecaryData[33].sciname;
              document.getElementById('commonName').innerText = apothecaryData[33].commonName;
              document.getElementById('clade').innerText = apothecaryData[33].clade;
              document.getElementById('division').innerText = apothecaryData[33].division;
              document.getElementById('plantOrder').innerText = apothecaryData[33].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[33].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[33].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[33].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[33].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[33].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[33].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[33].plantUse;
        }else if(data[0] == 35){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/katuray.png");
              document.getElementById('plantLabel').innerText = apothecaryData[34].commonName;
              document.getElementById('sciname').innerText = apothecaryData[34].sciname;
              document.getElementById('commonName').innerText = apothecaryData[34].commonName;
              document.getElementById('clade').innerText = apothecaryData[34].clade;
              document.getElementById('division').innerText = apothecaryData[34].division;
              document.getElementById('plantOrder').innerText = apothecaryData[34].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[34].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[34].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[34].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[34].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[34].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[34].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[34].plantUse;
        }else if(data[0] == 36){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Santan.png");
              document.getElementById('plantLabel').innerText = apothecaryData[35].commonName;
              document.getElementById('sciname').innerText = apothecaryData[35].sciname;
              document.getElementById('commonName').innerText = apothecaryData[35].commonName;
              document.getElementById('clade').innerText = apothecaryData[35].clade;
              document.getElementById('division').innerText = apothecaryData[35].division;
              document.getElementById('plantOrder').innerText = apothecaryData[35].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[35].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[35].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[35].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[35].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[35].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[35].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[35].plantUse;
        }else if(data[0] == 37){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/mirasol.png");
              document.getElementById('plantLabel').innerText = apothecaryData[36].commonName;
              document.getElementById('sciname').innerText = apothecaryData[36].sciname;
              document.getElementById('commonName').innerText = apothecaryData[36].commonName;
              document.getElementById('clade').innerText = apothecaryData[36].clade;
              document.getElementById('division').innerText = apothecaryData[36].division;
              document.getElementById('plantOrder').innerText = apothecaryData[36].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[36].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[36].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[36].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[36].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[36].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[36].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[36].plantUse;
        }else if(data[0] == 38){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/Roselle.png");
              document.getElementById('plantLabel').innerText = apothecaryData[37].commonName;
              document.getElementById('sciname').innerText = apothecaryData[37].sciname;
              document.getElementById('commonName').innerText = apothecaryData[37].commonName;
              document.getElementById('clade').innerText = apothecaryData[37].clade;
              document.getElementById('division').innerText = apothecaryData[37].division;
              document.getElementById('plantOrder').innerText = apothecaryData[37].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[37].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[37].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[37].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[37].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[37].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[37].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[37].plantUse;
        }else if(data[0] == 39){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pukingan.png");
              document.getElementById('plantLabel').innerText = apothecaryData[38].commonName;
              document.getElementById('sciname').innerText = apothecaryData[38].sciname;
              document.getElementById('commonName').innerText = apothecaryData[38].commonName;
              document.getElementById('clade').innerText = apothecaryData[38].clade;
              document.getElementById('division').innerText = apothecaryData[38].division;
              document.getElementById('plantOrder').innerText = apothecaryData[38].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[38].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[38].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[38].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[38].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[38].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[38].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[38].plantUse;
        }else if(data[0] == 40){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/alascuatro.png");
              document.getElementById('plantLabel').innerText = apothecaryData[39].commonName;
              document.getElementById('sciname').innerText = apothecaryData[39].sciname;
              document.getElementById('commonName').innerText = apothecaryData[39].commonName;
              document.getElementById('clade').innerText = apothecaryData[39].clade;
              document.getElementById('division').innerText = apothecaryData[39].division;
              document.getElementById('plantOrder').innerText = apothecaryData[39].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[39].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[39].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[39].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[39].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[39].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[39].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[39].plantUse;
        }else if(data[0] == 41){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/lumot.png");
              document.getElementById('plantLabel').innerText = apothecaryData[40].commonName;
              document.getElementById('sciname').innerText = apothecaryData[40].sciname;
              document.getElementById('commonName').innerText = apothecaryData[40].commonName;
              document.getElementById('clade').innerText = apothecaryData[40].clade;
              document.getElementById('division').innerText = apothecaryData[40].division;
              document.getElementById('plantOrder').innerText = apothecaryData[40].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[40].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[40].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[40].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[40].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[40].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[40].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[40].plantUse;
        }else if(data[0] == 42){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/liverwort.png");
              document.getElementById('plantLabel').innerText = apothecaryData[41].commonName;
              document.getElementById('sciname').innerText = apothecaryData[41].sciname;
              document.getElementById('commonName').innerText = apothecaryData[41].commonName;
              document.getElementById('clade').innerText = apothecaryData[41].clade;
              document.getElementById('division').innerText = apothecaryData[41].division;
              document.getElementById('plantOrder').innerText = apothecaryData[41].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[41].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[41].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[41].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[41].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[41].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[41].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[41].plantUse;
        }else if(data[0] == 43){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/whiskfern.png");
              document.getElementById('plantLabel').innerText = apothecaryData[42].commonName;
              document.getElementById('sciname').innerText = apothecaryData[42].sciname;
              document.getElementById('commonName').innerText = apothecaryData[42].commonName;
              document.getElementById('clade').innerText = apothecaryData[42].clade;
              document.getElementById('division').innerText = apothecaryData[42].division;
              document.getElementById('plantOrder').innerText = apothecaryData[42].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[42].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[42].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[42].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[42].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[42].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[42].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[42].plantUse;
        }else if(data[0] == 44){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/spikemoss.png");
              document.getElementById('plantLabel').innerText = apothecaryData[43].commonName;
              document.getElementById('sciname').innerText = apothecaryData[43].sciname;
              document.getElementById('commonName').innerText = apothecaryData[43].commonName;
              document.getElementById('clade').innerText = apothecaryData[43].clade;
              document.getElementById('division').innerText = apothecaryData[43].division;
              document.getElementById('plantOrder').innerText = apothecaryData[43].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[43].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[43].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[43].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[43].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[43].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[43].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[43].plantUse;
        }else if(data[0] == 45){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pako.png");
              document.getElementById('plantLabel').innerText = apothecaryData[44].commonName;
              document.getElementById('sciname').innerText = apothecaryData[44].sciname;
              document.getElementById('commonName').innerText = apothecaryData[44].commonName;
              document.getElementById('clade').innerText = apothecaryData[44].clade;
              document.getElementById('division').innerText = apothecaryData[44].division;
              document.getElementById('plantOrder').innerText = apothecaryData[44].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[44].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[44].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[44].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[44].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[44].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[44].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[44].plantUse;
        }else if(data[0] == 46){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/nito.png");
              document.getElementById('plantLabel').innerText = apothecaryData[45].commonName;
              document.getElementById('sciname').innerText = apothecaryData[45].sciname;
              document.getElementById('commonName').innerText = apothecaryData[45].commonName;
              document.getElementById('clade').innerText = apothecaryData[45].clade;
              document.getElementById('division').innerText = apothecaryData[45].division;
              document.getElementById('plantOrder').innerText = apothecaryData[45].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[45].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[45].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[45].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[45].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[45].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[45].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[45].plantUse;
        }else if(data[0] == 47){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/asola.png");
              document.getElementById('plantLabel').innerText = apothecaryData[46].commonName;
              document.getElementById('sciname').innerText = apothecaryData[46].sciname;
              document.getElementById('commonName').innerText = apothecaryData[46].commonName;
              document.getElementById('clade').innerText = apothecaryData[46].clade;
              document.getElementById('division').innerText = apothecaryData[46].division;
              document.getElementById('plantOrder').innerText = apothecaryData[46].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[46].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[46].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[46].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[46].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[46].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[46].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[46].plantUse;
        }else if(data[0] == 48){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/pitogo.png");
              document.getElementById('plantLabel').innerText = apothecaryData[47].commonName;
              document.getElementById('sciname').innerText = apothecaryData[47].sciname;
              document.getElementById('commonName').innerText = apothecaryData[47].commonName;
              document.getElementById('clade').innerText = apothecaryData[47].clade;
              document.getElementById('division').innerText = apothecaryData[47].division;
              document.getElementById('plantOrder').innerText = apothecaryData[47].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[47].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[47].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[47].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[47].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[47].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[47].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[47].plantUse;
        }else if(data[0] == 49){
              $("#plantImg").attr("src", "/IBS-PROJ/devtools/images/plants/bago.png");
              document.getElementById('plantLabel').innerText = apothecaryData[48].commonName;
              document.getElementById('sciname').innerText = apothecaryData[48].sciname;
              document.getElementById('commonName').innerText = apothecaryData[48].commonName;
              document.getElementById('clade').innerText = apothecaryData[48].clade;
              document.getElementById('division').innerText = apothecaryData[48].division;
              document.getElementById('plantOrder').innerText = apothecaryData[48].plantOrder;
              document.getElementById('habit').innerText = apothecaryData[48].d_habit;
              document.getElementById('rootsystem').innerText = apothecaryData[48].d_rootsystem;
              document.getElementById('stem').innerText = apothecaryData[48].d_stem;
              document.getElementById('leaftype').innerText = apothecaryData[48].d_leaftype;
              document.getElementById('phyllotaxy').innerText = apothecaryData[48].d_phyllotaxy;
              document.getElementById('ftype').innerText = apothecaryData[48].d_ftype;
              document.getElementById('plantUse').innerText = apothecaryData[48].plantUse;
        }



          //document.getElementById("plantImg").src = "bayabas.png";
    } );

    
});


 
